### ISSUE TITLE
Service ID PR merge breaks unit tests

### ISSUE THREAD

**Issue by gmazoyer** [peering-manager/peering-manager#406]
### Environment
* Python version:  3.9
* Peering Manager version:  commit 210a583

### Steps to Reproduce

Just run unit tests

### Expected Behavior

Tests pass

### Observed Behavior

```
2021-05-08T10:23:55.5145669Z ...............................................................................................................................E.E...................................E..E..E..................................E.......E............................................................................................................
2021-05-08T10:23:55.5146992Z ======================================================================
2021-05-08T10:23:55.5149954Z ERROR: setUpClass (peering.tests.test_filters.DirectPeeringSessionTestCase)
2021-05-08T10:23:55.5153079Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5156448Z Traceback (most recent call last):
2021-05-08T10:23:55.5158890Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5160121Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5161488Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "peering_directpeeringsession_service_reference_e2665ca2_uniq"
2021-05-08T10:23:55.5162824Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5163252Z 
2021-05-08T10:23:55.5163474Z 
2021-05-08T10:23:55.5164067Z The above exception was the direct cause of the following exception:
2021-05-08T10:23:55.5164579Z 
2021-05-08T10:23:55.5165006Z Traceback (most recent call last):
2021-05-08T10:23:55.5166537Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
2021-05-08T10:23:55.5167634Z     cls.setUpTestData()
2021-05-08T10:23:55.5168890Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_filters.py", line 189, in setUpTestData
2021-05-08T10:23:55.5170144Z     DirectPeeringSession.objects.bulk_create(
2021-05-08T10:23:55.5171882Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5173066Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5174486Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/query.py", line 374, in bulk_create
2021-05-08T10:23:55.5175650Z     objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
2021-05-08T10:23:55.5177136Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 514, in bulk_create
2021-05-08T10:23:55.5178216Z     returned_columns = self._batched_insert(
2021-05-08T10:23:55.5179647Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1287, in _batched_insert
2021-05-08T10:23:55.5180748Z     inserted_rows.extend(self._insert(
2021-05-08T10:23:55.5182127Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
2021-05-08T10:23:55.5183320Z     return query.get_compiler(using=using).execute_sql(returning_fields)
2021-05-08T10:23:55.5184898Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
2021-05-08T10:23:55.5186239Z     cursor.execute(sql, params)
2021-05-08T10:23:55.5187651Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/transaction.py", line 93, in execute
2021-05-08T10:23:55.5188827Z     result = self._no_monkey.execute(self, sql, params)
2021-05-08T10:23:55.5190285Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
2021-05-08T10:23:55.5191557Z     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2021-05-08T10:23:55.5193203Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2021-05-08T10:23:55.5194699Z     return executor(sql, params, many, context)
2021-05-08T10:23:55.5196140Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5197280Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5198796Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2021-05-08T10:23:55.5199986Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2021-05-08T10:23:55.5201487Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5202627Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5203942Z django.db.utils.IntegrityError: duplicate key value violates unique constraint "peering_directpeeringsession_service_reference_e2665ca2_uniq"
2021-05-08T10:23:55.5205242Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5205652Z 
2021-05-08T10:23:55.5205881Z 
2021-05-08T10:23:55.5206363Z ======================================================================
2021-05-08T10:23:55.5207599Z ERROR: setUpClass (peering.tests.test_filters.InternetExchangePeeringSessionTestCase)
2021-05-08T10:23:55.5209165Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5209805Z Traceback (most recent call last):
2021-05-08T10:23:55.5211179Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5212313Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5213594Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "peering_internetexchange_service_reference_40f6403f_uniq"
2021-05-08T10:23:55.5214854Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5215274Z 
2021-05-08T10:23:55.5215489Z 
2021-05-08T10:23:55.5216176Z The above exception was the direct cause of the following exception:
2021-05-08T10:23:55.5216638Z 
2021-05-08T10:23:55.5217031Z Traceback (most recent call last):
2021-05-08T10:23:55.5218357Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
2021-05-08T10:23:55.5219363Z     cls.setUpTestData()
2021-05-08T10:23:55.5220528Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_filters.py", line 335, in setUpTestData
2021-05-08T10:23:55.5222023Z     InternetExchangePeeringSession.objects.bulk_create(
2021-05-08T10:23:55.5225116Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5226340Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5227870Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/query.py", line 374, in bulk_create
2021-05-08T10:23:55.5229008Z     objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
2021-05-08T10:23:55.5230656Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 514, in bulk_create
2021-05-08T10:23:55.5231743Z     returned_columns = self._batched_insert(
2021-05-08T10:23:55.5233185Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1287, in _batched_insert
2021-05-08T10:23:55.5234585Z     inserted_rows.extend(self._insert(
2021-05-08T10:23:55.5235985Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
2021-05-08T10:23:55.5237174Z     return query.get_compiler(using=using).execute_sql(returning_fields)
2021-05-08T10:23:55.5238761Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
2021-05-08T10:23:55.5239865Z     cursor.execute(sql, params)
2021-05-08T10:23:55.5241361Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/transaction.py", line 93, in execute
2021-05-08T10:23:55.5242535Z     result = self._no_monkey.execute(self, sql, params)
2021-05-08T10:23:55.5244006Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
2021-05-08T10:23:55.5245280Z     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2021-05-08T10:23:55.5246923Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2021-05-08T10:23:55.5248092Z     return executor(sql, params, many, context)
2021-05-08T10:23:55.5260684Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5262206Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5264016Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2021-05-08T10:23:55.5265452Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2021-05-08T10:23:55.5267374Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5268667Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5269939Z django.db.utils.IntegrityError: duplicate key value violates unique constraint "peering_internetexchange_service_reference_40f6403f_uniq"
2021-05-08T10:23:55.5271929Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5272481Z 
2021-05-08T10:23:55.5272721Z 
2021-05-08T10:23:55.5273239Z ======================================================================
2021-05-08T10:23:55.5274551Z ERROR: setUpClass (peering.tests.test_models.DirectPeeringSessionTest)
2021-05-08T10:23:55.5276183Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5276981Z Traceback (most recent call last):
2021-05-08T10:23:55.5278795Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
2021-05-08T10:23:55.5280021Z     cls.setUpTestData()
2021-05-08T10:23:55.5281578Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_models.py", line 175, in setUpTestData
2021-05-08T10:23:55.5289039Z     cls.session = DirectPeeringSession.objects.create(
2021-05-08T10:23:55.5291098Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5315441Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5317619Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
2021-05-08T10:23:55.5339479Z     obj.save(force_insert=True, using=self.db)
2021-05-08T10:23:55.5340787Z   File "/home/runner/work/peering-manager/peering-manager/peering/models/abstracts.py", line 220, in save
2021-05-08T10:23:55.5341998Z     self.service_reference = self.generate_service_reference()
2021-05-08T10:23:55.5343517Z   File "/home/runner/work/peering-manager/peering-manager/peering/models/abstracts.py", line 210, in generate_service_reference
2021-05-08T10:23:55.5344583Z     asn = str(self.local_autonomous_system.asn)
2021-05-08T10:23:55.5345505Z AttributeError: 'NoneType' object has no attribute 'asn'
2021-05-08T10:23:55.5346141Z 
2021-05-08T10:23:55.5346534Z ======================================================================
2021-05-08T10:23:55.5348272Z ERROR: setUpClass (peering.tests.test_models.InternetExchangePeeringSessionTest)
2021-05-08T10:23:55.5349811Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5350467Z Traceback (most recent call last):
2021-05-08T10:23:55.5352150Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
2021-05-08T10:23:55.5353357Z     cls.setUpTestData()
2021-05-08T10:23:55.5355209Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_models.py", line 243, in setUpTestData
2021-05-08T10:23:55.5356974Z     cls.session = InternetExchangePeeringSession.objects.create(
2021-05-08T10:23:55.5359578Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5364883Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5366886Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
2021-05-08T10:23:55.5368088Z     obj.save(force_insert=True, using=self.db)
2021-05-08T10:23:55.5369435Z   File "/home/runner/work/peering-manager/peering-manager/peering/models/abstracts.py", line 220, in save
2021-05-08T10:23:55.5370651Z     self.service_reference = self.generate_service_reference()
2021-05-08T10:23:55.5372367Z   File "/home/runner/work/peering-manager/peering-manager/peering/models/abstracts.py", line 206, in generate_service_reference
2021-05-08T10:23:55.5373708Z     self.ixp_connection.internet_exchange_point.local_autonomous_system.asn
2021-05-08T10:23:55.5374832Z AttributeError: 'NoneType' object has no attribute 'asn'
2021-05-08T10:23:55.5375304Z 
2021-05-08T10:23:55.5375681Z ======================================================================
2021-05-08T10:23:55.5376477Z ERROR: test_get_configuration_context (peering.tests.test_models.RouterTest)
2021-05-08T10:23:55.5377598Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5378224Z Traceback (most recent call last):
2021-05-08T10:23:55.5379559Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_models.py", line 341, in test_get_configuration_context
2021-05-08T10:23:55.5380871Z     DirectPeeringSession.objects.create(
2021-05-08T10:23:55.5382546Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5383711Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5385136Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
2021-05-08T10:23:55.5386205Z     obj.save(force_insert=True, using=self.db)
2021-05-08T10:23:55.5387414Z   File "/home/runner/work/peering-manager/peering-manager/peering/models/abstracts.py", line 220, in save
2021-05-08T10:23:55.5388487Z     self.service_reference = self.generate_service_reference()
2021-05-08T10:23:55.5389959Z   File "/home/runner/work/peering-manager/peering-manager/peering/models/abstracts.py", line 210, in generate_service_reference
2021-05-08T10:23:55.5391200Z     asn = str(self.local_autonomous_system.asn)
2021-05-08T10:23:55.5392129Z AttributeError: 'NoneType' object has no attribute 'asn'
2021-05-08T10:23:55.5392603Z 
2021-05-08T10:23:55.5392975Z ======================================================================
2021-05-08T10:23:55.5394144Z ERROR: setUpClass (peering.tests.test_views.DirectPeeringSessionTestCase)
2021-05-08T10:23:55.5395457Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5396087Z Traceback (most recent call last):
2021-05-08T10:23:55.5397462Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5398637Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5399977Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "peering_directpeeringsession_service_reference_e2665ca2_uniq"
2021-05-08T10:23:55.5401286Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5401815Z 
2021-05-08T10:23:55.5402053Z 
2021-05-08T10:23:55.5402638Z The above exception was the direct cause of the following exception:
2021-05-08T10:23:55.5403135Z 
2021-05-08T10:23:55.5403580Z Traceback (most recent call last):
2021-05-08T10:23:55.5405019Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
2021-05-08T10:23:55.5406092Z     cls.setUpTestData()
2021-05-08T10:23:55.5407352Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_views.py", line 143, in setUpTestData
2021-05-08T10:23:55.5408581Z     DirectPeeringSession.objects.bulk_create(
2021-05-08T10:23:55.5410237Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5411414Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5412841Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/query.py", line 374, in bulk_create
2021-05-08T10:23:55.5413987Z     objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
2021-05-08T10:23:55.5415518Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 514, in bulk_create
2021-05-08T10:23:55.5416716Z     returned_columns = self._batched_insert(
2021-05-08T10:23:55.5418208Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1287, in _batched_insert
2021-05-08T10:23:55.5419339Z     inserted_rows.extend(self._insert(
2021-05-08T10:23:55.5420716Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
2021-05-08T10:23:55.5421924Z     return query.get_compiler(using=using).execute_sql(returning_fields)
2021-05-08T10:23:55.5423496Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
2021-05-08T10:23:55.5424589Z     cursor.execute(sql, params)
2021-05-08T10:23:55.5425980Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/transaction.py", line 93, in execute
2021-05-08T10:23:55.5427152Z     result = self._no_monkey.execute(self, sql, params)
2021-05-08T10:23:55.5428589Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
2021-05-08T10:23:55.5429864Z     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2021-05-08T10:23:55.5431511Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2021-05-08T10:23:55.5432784Z     return executor(sql, params, many, context)
2021-05-08T10:23:55.5434308Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5435448Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5436861Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2021-05-08T10:23:55.5438024Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2021-05-08T10:23:55.5439505Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5440645Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5441978Z django.db.utils.IntegrityError: duplicate key value violates unique constraint "peering_directpeeringsession_service_reference_e2665ca2_uniq"
2021-05-08T10:23:55.5443260Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5443768Z 
2021-05-08T10:23:55.5444008Z 
2021-05-08T10:23:55.5444376Z ======================================================================
2021-05-08T10:23:55.5445561Z ERROR: setUpClass (peering.tests.test_views.InternetExchangePeeringSessionTestCase)
2021-05-08T10:23:55.5447089Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5447718Z Traceback (most recent call last):
2021-05-08T10:23:55.5449087Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5450231Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5451511Z psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "peering_internetexchange_service_reference_40f6403f_uniq"
2021-05-08T10:23:55.5452785Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5453211Z 
2021-05-08T10:23:55.5453442Z 
2021-05-08T10:23:55.5454026Z The above exception was the direct cause of the following exception:
2021-05-08T10:23:55.5454525Z 
2021-05-08T10:23:55.5454967Z Traceback (most recent call last):
2021-05-08T10:23:55.5456365Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
2021-05-08T10:23:55.5457457Z     cls.setUpTestData()
2021-05-08T10:23:55.5458709Z   File "/home/runner/work/peering-manager/peering-manager/peering/tests/test_views.py", line 285, in setUpTestData
2021-05-08T10:23:55.5460148Z     InternetExchangePeeringSession.objects.bulk_create(
2021-05-08T10:23:55.5462033Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-05-08T10:23:55.5463210Z     return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-05-08T10:23:55.5464648Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/query.py", line 374, in bulk_create
2021-05-08T10:23:55.5465770Z     objs = self._no_monkey.bulk_create(self, objs, *args, **kwargs)
2021-05-08T10:23:55.5467238Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 514, in bulk_create
2021-05-08T10:23:55.5468320Z     returned_columns = self._batched_insert(
2021-05-08T10:23:55.5469918Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1287, in _batched_insert
2021-05-08T10:23:55.5471073Z     inserted_rows.extend(self._insert(
2021-05-08T10:23:55.5472498Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
2021-05-08T10:23:55.5473834Z     return query.get_compiler(using=using).execute_sql(returning_fields)
2021-05-08T10:23:55.5475542Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
2021-05-08T10:23:55.5476652Z     cursor.execute(sql, params)
2021-05-08T10:23:55.5478043Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/cacheops/transaction.py", line 93, in execute
2021-05-08T10:23:55.5479214Z     result = self._no_monkey.execute(self, sql, params)
2021-05-08T10:23:55.5480661Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
2021-05-08T10:23:55.5481930Z     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2021-05-08T10:23:55.5483584Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
2021-05-08T10:23:55.5484746Z     return executor(sql, params, many, context)
2021-05-08T10:23:55.5486252Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5487401Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5488810Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
2021-05-08T10:23:55.5489964Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2021-05-08T10:23:55.5491465Z   File "/home/runner/work/peering-manager/peering-manager/.tox/py39/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
2021-05-08T10:23:55.5492614Z     return self.cursor.execute(sql, params)
2021-05-08T10:23:55.5493861Z django.db.utils.IntegrityError: duplicate key value violates unique constraint "peering_internetexchange_service_reference_40f6403f_uniq"
2021-05-08T10:23:55.5495109Z DETAIL:  Key (service_reference)=() already exists.
2021-05-08T10:23:55.5495538Z 
2021-05-08T10:23:55.5495766Z 
2021-05-08T10:23:55.5496483Z ----------------------------------------------------------------------
2021-05-08T10:23:55.5497054Z Ran 335 tests in 19.046s
2021-05-08T10:23:55.5497339Z 
2021-05-08T10:23:55.5497701Z FAILED (errors=7)
```

**Comment by gmazoyer** [comment]
Service reference field has not default value, yet the model wants this field's value to be unique. This could be easily fixed by using a generated default value. However the current generation function needs to know session's properties that cannot be fetched when creating a session in the database. There are more than one "fix" for this behaviour:

1. Make the default value of the service reference field independent from session's properties, but we'll lose the nice way to generate the reference in favour of something random
2. Make the service reference field non unique, several session could have the same service ID, feels weird …

Note that this only applies when create sessions without using forms as using form will call `BGPSession.save()`, therefore generating the service ID, based on model's properties set before actually saving the values in the database

**Comment by jamesditrapani** [comment]
Hmm, this is a hard one but 100% needs a resolution before next release. I'll discuss this with you over Slack. 

Note for later: Need to ensure we return `service_reference` via the API views for all BGPSession submodels.
