### ISSUE TITLE
column "config_context" of relation "peering_router" already exists

### ISSUE THREAD

**Issue by freedomwarrior** [peering-manager/peering-manager#475]
Python version: Python 3.8.10

After upgrading to 1.4.5-dev I got this error:
```
The complete exception is provided below:

              <class 'django.db.utils.ProgrammingError'>
              

              column "prechange_data" of relation "utils_objectchange" does not exist
LINE 1: ...ect_type_id", "related_object_id", "object_repr", "prechange...
                                                             ^

              

              Python version: 
              Peering Manager version: 
```

Then I try to run migrate and got this error:
```
(venv) root@peering-manager:/opt/peering-manager# python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, devices, extras, net, peering, peeringdb, sessions, taggit, users, utils, webhooks
Running migrations:
  Applying peering.0074_add_configcontext...Traceback (most recent call last):
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "config_context" of relation "peering_router" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 522, in add_field
    self.execute(sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/cacheops/transaction.py", line 97, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "config_context" of relation "peering_router" already exists
```

**Comment by jamesditrapani** [comment]
Looks like the migration for 0074_add_configcontext has already been run as the DB schema matches what we attempt to add. As a test, can you try running this:

```python
./manage.py migrate --fake peering 0074_add_configcontext
```

and then:
```python
./manage.py migrate
```

**Comment by freedomwarrior** [comment]
> Looks like the migration for 0074_add_configcontext has already been run as the DB schema matches what we attempt to add. As a test, can you try running this:
> 
> ```python
> ./manage.py migrate --fake peering 0074_add_configcontext
> ```
> 
> and then:
> 
> ```python
> ./manage.py migrate
> ```

Got error:
```
(venv) root@peering-manager:/opt/peering-manager# ./manage.py migrate --fake peering 0074_add_configcontext
Operations to perform:
  Target specific migration: 0074_add_configcontext, from peering
Running migrations:
  Applying peering.0074_add_configcontext... FAKED
```
```
(venv) root@peering-manager:/opt/peering-manager# ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, devices, extras, net, peering, peeringdb, sessions, taggit, users, utils, w                                               ebhooks
Running migrations:
  Applying peering.0075_auto_20210604_1709...Traceback (most recent call last):
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "service_reference" of relation "peering_directpeeringsession" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_c                                               ommand_line
    utility.execute()
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_for                                               wards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 104, in databas                                               e_forwards
    schema_editor.add_field(
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 522, in add_field
    self.execute(sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/cacheops/transaction.py", line 97, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "service_reference" of relation "peering_directpeeringsession" already exists
```

**Comment by jamesditrapani** [comment]
So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?

**Comment by freedomwarrior** [comment]
> So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?



> So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?

I can't tell exactly from what version I was upgrading but I think that It was between 1.4.0-1.4.2
And I was upgrading this way:
```
git pull
./scripts/upgrade.sh
```
After that, in web, I got error, and there was instruction to run migrate manualy.
That's all I do.

**Comment by jamesditrapani** [comment]
> > So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?
> 
> > So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?
> 
> I can't tell exactly from what version I was upgrading but I think that It was between 1.4.0-1.4.2
> And I was upgrading this way:
> 
> ```
> git pull
> ./scripts/upgrade.sh
> ```
> 
> After that, in web, I got error, and there was instruction to run migrate manualy.
> That's all I do.

Running `upgrade.sh` should automatically perform database migrations. Can you do a fake migration on `0075_auto_20210604_1709` and provide the output of `./manage.py showmigrations`.

**Comment by freedomwarrior** [comment]
> > > So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?
> > 
> > 
> > > So it looks like migration `peering/0075_auto_20210604_1709` has also already been run. What version did you updgrade from? Have you already run these migrations previously?
> > 
> > 
> > I can't tell exactly from what version I was upgrading but I think that It was between 1.4.0-1.4.2
> > And I was upgrading this way:
> > ```
> > git pull
> > ./scripts/upgrade.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that, in web, I got error, and there was instruction to run migrate manualy.
> > That's all I do.
> 
> Running `upgrade.sh` should automatically perform database migrations. Can you do a fake migration on `0075_auto_20210604_1709` and provide the output of `./manage.py showmigrations`.

```
(venv) root@peering-manager:/opt/peering-manager# ./manage.py migrate --fake peering 0075_auto_20210604_1709
Operations to perform:
  Target specific migration: 0075_auto_20210604_1709, from peering
Running migrations:
  Applying peering.0075_auto_20210604_1709... FAKED
(venv) root@peering-manager:/opt/peering-manager# ./manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
devices
 [X] 0001_initial
 [X] 0002_alter_platform_id
extras
 [X] 0001_initial
 [X] 0002_alter_jobresult_id
 [X] 0003_webhook
net
 [X] 0001_initial
 [ ] 0002_alter_connection_internet_exchange_point
peering
 [X] 0001_initial
 [X] 0002_auto_20170820_1809
 [X] 0003_auto_20170903_1235
 [X] 0004_auto_20171004_2323
 [X] 0005_auto_20171014_1427
 [X] 0006_auto_20171017_1917
 [X] 0007_auto_20171202_1900
 [X] 0008_auto_20171212_2251
 [X] 0009_auto_20171226_1550
 [X] 0010_auto_20171228_0158
 [X] 0011_auto_20180329_2146
 [X] 0012_auto_20180502_1733
 [X] 0013_auto_20180505_1545
 [X] 0014_auto_20180519_2128
 [X] 0015_peeringsession_password
 [X] 0016_auto_20180726_1307
 [X] 0017_auto_20180802_2309
 [X] 0018_auto_20181014_1612
 [X] 0019_router_netbox_device_id
 [X] 0020_auto_20181105_0850
 [X] 0021_auto_20181113_2136
 [X] 0022_auto_20181116_2226
 [X] 0023_auto_20181208_2202
 [X] 0024_auto_20181212_2106
 [X] 0025_auto_20181212_2322
 [X] 0026_autonomoussystem_potential_internet_exchange_peering_sessions
 [X] 0027_auto_20190105_1600
 [X] 0028_internetexchangepeeringsession_is_router_server
 [X] 0029_auto_20190114_2141
 [X] 0030_directpeeringsession_router
 [X] 0031_auto_20190227_2210
 [X] 0032_auto_20190302_1415
 [X] 0033_router_encrypt_passwords
 [X] 0034_auto_20190308_1954
 [X] 0035_auto_20190311_2334
 [X] 0036_auto_20190411_2209
 [X] 0037_auto_20190412_2102
 [X] 0038_auto_20190412_2233
 [X] 0039_routingpolicy_address_family
 [X] 0040_auto_20190417_1851
 [X] 0041_auto_20190430_1743
 [X] 0042_auto_20190509_1439
 [X] 0043_router_use_netbox
 [X] 0044_auto_20190513_2153
 [X] 0045_auto_20190514_2308
 [X] 0046_auto_20190608_2215
 [X] 0047_auto_20190619_1434
 [X] 0048_auto_20190707_1854
 [X] 0049_auto_20190731_1946
 [X] 0050_auto_20190806_2159
 [X] 0051_auto_20190818_1816
 [X] 0052_auto_20190818_1926
 [X] 0053_auto_20190921_2000
 [X] 0054_auto_20191031_2241
 [X] 0055_auto_20191110_1312
 [X] 0056_autonomoussystem_prefixes
 [X] 0057_auto_20200509_1629
 [X] 0058_autonomoussystem_name_peeringdb_sync
 [X] 0059_router_last_deployment_id
 [X] 0060_auto_20200718_0023
 [X] 0061_community_slug
 [X] 0062_auto_20200805_2322
 [X] 0063_auto_20200807_1503
 [X] 0064_auto_20201016_2113
 [X] 0065_auto_20201025_2137
 [X] 0066_auto_20201212_2301
 [X] 0067_auto_20210112_1318
 [X] 0068_router_device_state
 [X] 0069_auto_20210212_1850
 [X] 0070_remove_router_last_deployment_id
 [X] 0071_auto_20210321_1843
 [X] 0072_auto_20210420_2144
 [X] 0073_auto_20210425_1303
 [X] 0074_add_configcontext
 [X] 0075_auto_20210604_1709
 [ ] 0076_autonomoussystem_communities
 [ ] 0077_alter_router_device_state
peeringdb
 [X] 0001_initial
 [X] 0002_auto_20180101_0203
 [X] 0003_networkixlan_name
 [X] 0004_auto_20180121_2207
 [X] 0005_auto_20180122_1845
 [X] 0006_auto_20180213_0031
 [X] 0007_peerrecord
 [X] 0008_auto_20181212_2106
 [X] 0009_auto_20181212_2322
 [X] 0010_auto_20190417_1851
 [X] 0011_contact
 [X] 0012_peerrecord_visible
 [X] 0013_auto_20201207_2233
 [X] 0014_auto_20201208_1856
 [X] 0015_auto_20210227_1258
 [X] 0016_auto_20210420_2144
 [X] 0017_auto_20210425_1229
 [X] 0018_auto_20210523_1204
sessions
 [X] 0001_initial
taggit
 [X] 0001_initial
 [X] 0002_auto_20150616_2121
 [X] 0003_taggeditem_add_unique_index
users
 [X] 0001_initial
 [X] 0002_userpreferences
 [X] 0003_auto_20200805_2322
 [X] 0004_auto_20210420_2144
utils
 [X] 0001_initial
 [X] 0002_auto_20180329_2146
 [X] 0003_auto_20181112_2150
 [X] 0004_auto_20181208_2202
 [X] 0005_tag_taggeditem
 [X] 0006_auto_20200626_2340
 [X] 0007_auto_20200805_2322
 [X] 0008_auto_20210420_2144
 [ ] 0009_auto_20210721_1414
 [ ] 0010_auto_20210721_1415
 [ ] 0011_auto_20210721_1428
webhooks
 [X] 0001_initial
 [X] 0002_alter_webhook_id
 [X] 0003_move_to_extras

```

**Comment by jamesditrapani** [comment]
Hey @freedomwarrior, go ahead and run a standard migration via:

`./manage.py migrate peering`

If you get an error on `0076_autonomoussystem_communities` or `0077_alter_router_device_state`, fake these migrations through. Once that is done, you should be able to run a `./manage.py migrate` to migrate everything else, if that errors to attempt to just migrate utils only: `./manage.py migrate utils`.

Can you let me know any errors you see while doing the above so I can try & track down what went wrong.

**Comment by freedomwarrior** [comment]
> Hey @freedomwarrior, go ahead and run a standard migration via:
> 
> `./manage.py migrate peering`
> 
> If you get an error on `0076_autonomoussystem_communities` or `0077_alter_router_device_state`, fake these migrations through. Once that is done, you should be able to run a `./manage.py migrate` to migrate everything else, if that errors to attempt to just migrate utils only: `./manage.py migrate utils`.
> 
> Can you let me know any errors you see while doing the above so I can try & track down what went wrong.

Yea, it works.
Thank you!
