### ISSUE TITLE
Failed job handling inconsistent

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#521]
### Peering Manager version

v1.4.6

### Python version

3.10

### Steps to Reproduce

Two different error scenarios, two different behaviours

*Scenario 1*
1. Set NAPALM_TIMEOUT 1
2. Manually deploy config
3. Deploy is likely to timeout
4. Job will be left in running state

*Scenario 2*
1. Submit Junos config with an error from the UI
2. Job errors out
3. Router left in locked exclusive state with pending commit

Have to manually roll back and logout the NETCONF session to recover router

### Expected Behavior

In scenario 1, I would expect the timeout to be caught and the job to move into an error state

In scenario 2, I would expect the job to discard the commit and release the lock on the router

### Observed Behavior

In scenario 1, the job is left in running state although the NAPALM connection been disconnected

In scenario 2, the job is in error state, but the router is left in an inconsistent state that requires manual intervention to bring it back into working order.

**Comment by gmazoyer** [comment]
What do you see in the `/admin/background-tasks` failed jobs? Do you see a stack trace of some sort with an uncaught exception?

**Comment by mngan** [comment]
This is what I see from from the ones left in the `running` state (i.e scenario 1)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jnpr/junos/device.py", line 1432, in close
    self._conn.close_session()
  File "/usr/local/lib/python3.10/site-packages/ncclient/manager.py", line 226, in execute
    return cls(self._session,
  File "/usr/local/lib/python3.10/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/usr/local/lib/python3.10/site-packages/ncclient/operations/rpc.py", line 366, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1043, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 814, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 837, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/opt/peering-manager/peering/jobs.py", line 106, in set_napalm_configuration
    error, changes = router.set_napalm_configuration(
  File "/opt/peering-manager/peering/models/models.py", line 1404, in set_napalm_configuration
    closed = self.close_napalm_device(device)
  File "/opt/peering-manager/peering/models/models.py", line 1311, in close_napalm_device
    device.close()
  File "/usr/local/lib/python3.10/site-packages/napalm/junos/junos.py", line 157, in close
    self.device.close()
  File "/usr/local/lib/python3.10/site-packages/jnpr/junos/device.py", line 1434, in close
    raise EzErrors.RpcTimeoutError(self, "close", self.timeout)
jnpr.junos.exception.RpcTimeoutError: RpcTimeoutError(host: bg1-bom1.nm.valve.net, cmd: close, timeout: 10)
```

**Comment by mngan** [comment]
We have some old slow devices and the default timeout of 10 was not long enough. Winding this up to 60 seconds ensures this doesn't happen, but it is still an edge case where things aren't being handled correctly.

**Comment by gmazoyer** [comment]
Commit 91ce67c should at least solve the connection close timeout. Scenario 2 looks like a library issue but we can try finding a way to mitigate it.

**Comment by mngan** [comment]
I think if you `discard_config()` in the exception handler, that should address the issue?

**Comment by gmazoyer** [comment]
Do you have a raised exceptions scenario 2 that could be the trigger to call `discard_config()`?

**Comment by mngan** [comment]
I think so. i had an error in my template which sent an invalid config which i believe throws an exception with napalm. It looks like Peering Manager catches that but just sets the error message and then closes the session without cleaning up. This also leaves the config locked on Junos which makes recovery just that much more difficult.

**Comment by gmazoyer** [comment]
I hope dedb464 will help to fix it. I'll try to test this myself once I'll have a decent lab to work with.

**Comment by mngan** [comment]
This looks like it should work. I'll see if I can check this out over the next week.
