### ISSUE TITLE
AttributeError: Can't pickle local object 'IOSDriver.get_bgp_neighbors_detail.<locals>.<lambda>'

### ISSUE THREAD

**Issue by ekrichbaum** [peering-manager/peering-manager#548]
### Peering Manager version

v1.5.3-dev

### Python version

3.10

### Steps to Reproduce

1. cronjob item (run manually) - cd /opt/peering-manager && venv/bin/python3 manage.py poll_peering_sessions --all

### Expected Behavior

Completion without error

### Observed Behavior
```
[root@peeringmgr peering-manager]# cd /opt/peering-manager && venv/bin/python3 manage.py poll_peering_sessions --all
[*] Polling peering sessions for BGP groups
[*] Polling peering sessions for Internet Exchanges
Traceback (most recent call last):
  File "/opt/peering-manager/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peering/management/commands/poll_peering_sessions.py", line 37, in handle
    internet_exchange.poll_peering_sessions()
  File "/usr/lib64/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/peering-manager/peering/models/models.py", line 784, in poll_peering_sessions
    bgp_neighbors_detail = router.get_bgp_neighbors_detail()
  File "/opt/peering-manager/peering/models/models.py", line 1681, in get_bgp_neighbors_detail
    return _get_bgp_neighbors_detail()
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/cacheops/query.py", line 131, in wrapper
    cache_thing(prefix, cache_key, result, cond_dnfs, timeout, dbs=dbs,
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/cacheops/redis.py", line 17, in handle_connection_failure
    return call()
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/peering-manager/venv/lib64/python3.10/site-packages/cacheops/query.py", line 54, in cache_thing
    settings.CACHEOPS_SERIALIZER.dumps(data),
AttributeError: Can't pickle local object 'IOSDriver.get_bgp_neighbors_detail.<locals>.<lambda>'
```

**Comment by gmazoyer** [comment]
What version of Redis are you using?

**Comment by ekrichbaum** [comment]
redis.x86_64                                                                             6.2.6-1.fc35                                                     @updates             

I removed the Cisco boxes from the poll and it works without any issues (as per the error).  The cisco boxes do work from the GUI button though.

**Comment by gmazoyer** [comment]
It looks like some caching failure more or less specific to the NAPALM IOS driver. I'm unable to reproduce it with the JUNOS one. We can probably mitigate it by excluding IOS NAPALM calls to be cached but we'll try to come up with a better solution first.

**Comment by ekrichbaum** [comment]
I'm not real familiar with Python enough to try to get to the point of helping much.  They are IOS XE boxes if that makes a difference but I''ve been steadily replacing them with Junipers.

**Comment by paketb0te** [comment]
napalm-automation/napalm/issues/2161

**Comment by paketb0te** [comment]
@gmazoyer FYI, napalm-automation/napalm/pull/2163 which fixes this issue has been merged - will probably take a while until they release a new version though.
