### ISSUE TITLE
Cannot delete some instances of model 'ContentType' because they are referenced through protected foreign keys: 'ObjectChange.changed_object_type'

### ISSUE THREAD

**Issue by netravnen** [peering-manager/peering-manager#738]
### Peering Manager version

v1.8.0-dev@3f8b9662

### Python version

3.10

### Steps to Reproduce

Follow the regular upgrade procedure from installation using tags running from commit 4ae81525 to commit 3f8b9662

### Expected Behavior

A successful migration.

### Observed Behavior

```
🔄 Removing stale content types
Traceback (most recent call last):
  File "/opt/peering-manager/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/contrib/contenttypes/management/commands/remove_stale_contenttypes.py", line 99, in handle
    ct.delete()
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1117, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/peering-manager/venv/lib/python3.10/site-packages/django/db/models/deletion.py", line 350, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'ContentType' because they are referenced through protected foreign keys: 'ObjectChange.changed_object_type'.", {<ObjectChange: tag BGP: created by adminuser>, <ObjectChange: tag Passive created by adminuser>, <ObjectChange: tag Session created by adminuser>, <ObjectChange: tag BGP-Session-Passive created by adminuser>, <ObjectChange: tag BGP: deleted by adminuser>, <ObjectChange: tag Passive deleted by adminuser>, <ObjectChange: tag Session deleted by adminuser>, <ObjectChange: tag BGP-Session-Passive updated by adminuser>, <ObjectChange: tag BGP-Session-Passive updated by adminuser>, <ObjectChange: tag Default-Policy updated by adminuser>, <ObjectChange: tag depref-50 updated by adminuser>, <ObjectChange: tag Fallback-Policy updated by adminuser>, <ObjectChange: tag no-advertise updated by adminuser>, <ObjectChange: tag Prefix-Preference updated by adminuser>, <ObjectChange: tag Default-Contact created by adminuser>})
```

**Comment by netravnen** [comment]
I assume if I update the references. The protection will disappear and the protected tags will be cleaned up during the next run of the migration script... :thinking:

**Comment by gmazoyer** [comment]
Yes some pieces are missing to cleanup old `ObjectChange`s referencing `Tag`s. I need to address that.
