### ISSUE TITLE
Failing to sync facilities from PeeringDB

### ISSUE THREAD

**Issue by Paktosan** [peering-manager/peering-manager#765]
### Peering Manager version

v1.8.1, also happens on v1.7.4

### Python version

3.9

### Steps to Reproduce

1. Run `venv/bin/python3 manage.py peeringdb_sync`
2. Observe exception

### Expected Behavior

Creation of facilites.

### Observed Behavior

```
APP | DEBUG | calling api: https://www.peeringdb.com/api/fac | {'since': 1674869413, 'depth': 0}
APP | DEBUG | Starting new HTTPS connection (1): www.peeringdb.com:443
APP | DEBUG | https://www.peeringdb.com:443 "GET /api/fac?since=1674869413&depth=0 HTTP/1.1" 200 None
[*] Caching data locally ... Traceback (most recent call last):
  File "/opt/peering-manager/peeringdb/sync.py", line 260, in synchronise_objects
    local_object, action = self._process_object(model, data)
  File "/opt/peering-manager/peeringdb/sync.py", line 198, in _process_object
    local_object = model.objects.get(pk=data["id"])
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/db/models/query.py", line 121, in __iter__
    for row in compiler.results_iter(results):
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/db/models/sql/compiler.py", line 1500, in apply_converters
    value = converter(value, expression, connection)
  File "/opt/peering-manager/peeringdb/models.py", line 107, in from_db_value
    self.clean_choices(values)
  File "/opt/peering-manager/peeringdb/models.py", line 83, in clean_choices
    raise ValidationError(f"Invalid value: {value}")
django.core.exceptions.ValidationError: ['Invalid value: []']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/peering-manager/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/peeringdb/management/commands/peeringdb_sync.py", line 46, in handle
    api.update_local_database(api.get_last_sync_time())
  File "/opt/peering-manager/peeringdb/sync.py", line 302, in update_local_database
    changes = self.synchronise_objects(last_sync, namespace, object_type)
  File "/opt/peering-manager/peeringdb/sync.py", line 268, in synchronise_objects
    f"error validating id: {local_object.id} for model: {model._meta.verbose_name.lower()}\n{e}"
UnboundLocalError: local variable 'local_object' referenced before assignment
```

**Comment by gmazoyer** [comment]
This may be a one off. Did you try to flush the PeeringDB local cache and attempt a synchronisation after?

**Comment by Paktosan** [comment]
Totally forgot about this issue, oops...
Clearing the cache and then resyncing fixed the issue.
