### ISSUE TITLE
Cannot delete some instances of model 'ContentType' because they are referenced through protected foreign keys

### ISSUE THREAD

**Issue by virtual-technologies** [peering-manager/peering-manager#838]
### Peering Manager version

v1.8.3

### Python version

3.10

### Steps to Reproduce

Trying to upgrade and get the following error

### Expected Behavior

should remove stale content types without errors.

### Observed Behavior

Running migrations:
  No migrations to apply.
🔄 Collecting static files

190 static files copied to '/opt/peering-manager/static', 2250 unmodified.
🔄 Removing stale content types
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/contrib/contenttypes/management/commands/remove_stale_contenttypes.py", line 99, in handle
    ct.delete()
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/models/base.py", line 1131, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "/opt/peering-manager/venv/lib/python3.8/site-packages/django/db/models/deletion.py", line 355, in collect
    raise ProtectedError(
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'ContentType' because they are referenced through protected foreign keys: 'ObjectChange.changed_object_type'.", {<ObjectChange: configuration test updated by admin>, <ObjectChange: configuration test created by admin>, <ObjectChange: configuration Goolge-out created by admin>})

**Comment by gmazoyer** [comment]
The stable content types remover command prevents you from deleting some content types because you still have change logs that refer to them. It can come from the fact that you upgraded from a quite old version to a very recent one in a very short period of time.

The problematic content type seem to be the one that was attached to configuration templates before they were moved to the `devices` module. If you want to unblock the situation you can try to clear the problematic entries in the `extras_objectchange` database table. Alternatively, you can try to run the `housekeeping` command to see if it clears out the problematic entries.

**Comment by virtual-technologies** [comment]
Thanks. Issue solved.
